### ISSUE TITLE
Problem finding src directory in Cordova project

### ISSUE THREAD

**Issue by ashe540** [Dynatrace/Dynatrace-Cordova-Plugin#1]
Hello, we are finding some difficulties instrumenting a Cordova application with the plugin. It seems that it fails to find a "src" directory (which the application does not have, since it is not an ionic application, but only cordova).

#INFO  [2017-06-19 12:44:20]: Successfully read the settings for the JSAgent instrumentation!
#INFO  [2017-06-19 12:44:20]: Auto-Update is turned on. Will try to update JSAgent.
#INFO  [2017-06-19 12:44:20]: Starting the download of the JSAgent ..
#INFO  [2017-06-19 12:44:20]: Download of agent file finished
#INFO  [2017-06-19 12:44:20]: JSAgent was downloaded successfully!
#INFO  [2017-06-19 12:44:20]: Path: C:\XXX\plugins\dynatrace-cordova-plugin\scripts/../../../src
#ERROR [2017-06-19 12:44:20]: Source directory is not available. There is nothing to instrument.
#ERROR [2017-06-19 12:44:20]: Error: Source directory is not available. There is nothing to instrument.
Error: Source directory is not available. There is nothing to instrument.

We have commented lines 87-135 of the instrument.js file, which is the part that checks for said directory and the instrumentation works fine. Shouldn't having this directory be optional and not exit the script? Thanks!

**Comment by TheHighriser** [comment]
In the beginning this was the case but I have changed that behaviour. The user can now define the custom directory via "custom_src_dir" : "www" in the package.json file. But you are right I should at least check for a www folder. I will change that. Thanks!

**Comment by ashe540** [comment]
That was something we tried as well, the exact same path that you mentioned. Simply adding that key value pair to the package.json should have been enough right? Or does it need to somewhere in particular?

**Comment by TheHighriser** [comment]
If you have set custom_src_dir it will not search in the "src" folder. I have tested it again and for me it works. In your logs I see that it searches in the "src" folder. Did you exactly use "custom_src_dir" : "www" ?

**Comment by TheHighriser** [comment]
@ashe540 : I have commited a fix for this. I should now be handled better. 

a596b76a04be0641c1b95b9214e223ce54b44c81

Please inform me if the bug is fixed.

**Comment by TheHighriser** [comment]
@ashe540 : I assume this is fixed, as you didn't report any problem. I will close the case. Feel free to open it again.
