### ISSUE TITLE
Unable to find dtAgent.js

### ISSUE THREAD

**Issue by kmanasa16** [Dynatrace/Dynatrace-Cordova-Plugin#2]
Followed the steps as per the documentation,

Successfully added cordova plugin by running the following command:
cordova plugin add dynatrace-cordova-plugin --save

When I try to build my cordova package it throws the following error:

> #INFO  [2018-08-02 19:11:18]: Starting the download of the JSAgent ..
> #ERROR [2018-08-02 19:11:18]: Could not download the JSAgent!
> #INFO  [2018-08-02 19:11:18]: Searching for HTML files ..
> #INFO  [2018-08-02 19:11:18]: Found main HTML file: /projectdir/platforms/android/assets/www/main.html
> #INFO  [2018-08-02 19:11:18]: Successfully instrumented: /projectdir/platforms/android/assets/www/main.html
> #INFO  [2018-08-02 19:11:18]: 1 HTML file(s) are instrumented.
> Could not read agent from download directory: Error: ENOENT: no such file or directory, open '/projectdir/plugins/dynatrace-cordova-plugin/scripts/../files/dtAgent.js'
> (node:804) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not read agent from download directory: Error: ENOENT: no such file or directory, open '/projectdir/plugins/dynatrace-cordova-plugin/scripts/../files/dtAgent.js'

I tried checking the dynatrace cordova plugin directory but was unable to find the dtagent . Is it related to "Could not download the JSAgent". Need Help

**Comment by TheHighriser** [comment]
Did you use the new version which is available over NPM? Because this GIT repository is way outdated? Your problem is already visible in the log. #ERROR [2018-08-02 19:11:18]: Could not download the JSAgent! - You can't download the JSAgent. Please use the newest NPM version. https://www.npmjs.com/package/dynatrace-cordova-plugin
