### ISSUE TITLE
Unable to view service calls on dashboard

### ISSUE THREAD

**Issue by kmanasa16** [Dynatrace/Dynatrace-Cordova-Plugin#3]
Integrated the plugin successfully but unable to view anything on dashboard under "services"
<img width="211" alt="screen shot 2018-08-13 at 5 13 54 pm" src="https://user-images.githubusercontent.com/42050051/44061038-67d07a34-9f1c-11e8-8cc7-7638efb56172.png">

**Comment by TheHighriser** [comment]
As this a pretty big topic which needs more clearance, please open a support ticket on dynatrace.com.
